import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ru';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

export const translations: Translations = {
  en: {
    nav_home: 'Home',
    nav_explore: 'Explore',
    nav_shorts: 'Shorts',
    nav_subscriptions: 'Subscriptions',
    nav_trending: 'Trending',
    nav_library: 'Library',
    nav_history: 'History',
    nav_continue_watching: 'Continue watching',
    nav_you: 'You',
    nav_your_channel: 'Your channel',
    nav_playlists: 'Playlists',
    nav_your_videos: 'Your Videos',
    nav_favorites: 'Favorites',
    favorites_title: 'Saved Videos',
    favorites_empty: 'You haven\'t saved any videos yet. Videos you save will appear here.',
    history_title: 'History',
    history_empty: 'Your watch history is empty.',
    history_clear: 'Clear all watch history',
    history_clear_confirm: 'Are you sure you want to clear your entire watch history?',
    liked_title: 'Liked Videos',
    liked_empty: 'You haven\'t liked any videos yet.',
    liked_login_required: 'Please sign in to see your liked videos.',
    nav_top_channels: 'Top Channels',
    top_channels_title: 'Channel Leaderboard',
    top_channels_by_subs: 'By Subscribers',
    top_channels_by_views: 'By Views',
    top_channels_by_likes: 'By Likes',
    top_channels_by_videos: 'By Videos',
    top_channels_empty: 'No leaderboard data available yet.',
    nav_downloads: 'Downloads',
    nav_clips: 'Clips',
    nav_watch_later: 'Watch Later',
    nav_navigator: 'Explore',
    nav_music: 'Music',
    nav_movies: 'Movies & TV',
    nav_live: 'Live',
    nav_more_features: 'More from Icetube',
    nav_premium: 'Icetube Premium',
    nav_yt_music: 'Icetube Music',
    nav_yt_kids: 'Icetube Kids',
    nav_liked: 'Liked videos',
    nav_settings: 'Settings',
    nav_admin: 'Admin Panel',
    nav_sign_in: 'Sign in',
    nav_sign_out: 'Sign Out',
    nav_subscriptions_header: 'Subscriptions',
    nav_socials: 'Our socials',
    nav_telegram: 'Telegram Channel',
    nav_show_more: 'Show more',
    nav_upload: 'Upload Video',
    search_placeholder: 'Search Icetube...',
    hero_no_videos: 'No videos yet',
    hero_upload_prompt: 'Be the first to upload a video using the button top right!',
    your_vids_title: 'Your Videos',
    your_vids_subtitle: 'Manage and watch your uploaded content',
    your_vids_upload_btn: 'Upload New Video',
    your_vids_login_req: 'Login Required',
    your_vids_login_desc: 'You need to be signed in to view and manage your uploaded videos.',
    settings_title: 'Settings',
    settings_subtitle: 'Settings are saved automatically',
    settings_theme: 'Theme',
    settings_theme_desc: 'Choose the visual appearance of the site',
    settings_dark: 'Dark',
    settings_light: 'Light',
    settings_lang: 'Language',
    settings_lang_desc: 'Select the primary interface language',
    settings_ru: 'Russian',
    settings_en: 'English',
    video_views: 'views',
    video_recently: 'Recently',
    video_no_description: 'No description provided.',
    nav_studio: 'Icetube Studio',
    studio_title: 'Channel Analytics',
    studio_total_views: 'Total Views',
    studio_total_videos: 'Total Videos',
    studio_content: 'Channel Content',
    studio_edit: 'Edit',
    studio_delete: 'Delete',
    video_no_results: 'No videos found',
    video_search_try_again: 'Try searching for something else or pick a different category.',
    video_connecting: 'Connecting to Server...',
    video_comments: 'Comments',
    video_sign_in_comment: 'Sign in to leave a comment',
    video_not_found: 'Video not found',
    video_not_found_desc: 'This video may have been deleted or does not exist.',
    video_subscribers: 'subscribers',
    video_subscribed: 'Subscribed',
    video_subscribe: 'Subscribe',
    video_share: 'Share',
    video_save: 'Save',
    video_saved: 'Saved',
    video_add_to_playlist: 'Add to playlist',
    video_watch_later: 'Watch later',
    video_added_to_watch_later: 'In Watch later',
    watch_later_title: 'Watch Later',
    watch_later_empty: 'Your Watch Later list is empty. Add videos you want to watch later here.',
    video_snowflakes: 'Snowflakes',
    video_views_time: 'views • {time} ago',
    video_more: '...more',
    video_less: 'Show less',
    comment_sort: 'Sort by',
    comment_translate: 'Translate to English',
    comment_edit: 'Edit',
    comment_delete: 'Delete',
    comment_reply: 'Reply',
    comment_save: 'Save',
    comment_cancel: 'Cancel',
    comment_placeholder: 'Add a comment...',
    comment_reply_placeholder: 'Add a reply...',
    studio_video_header: 'Video',
    studio_date_header: 'Date',
    studio_views_header: 'Views',
    studio_no_videos: 'No videos found. Upload your first clip to start tracking!',
    studio_back_home: 'Back to Home',
    studio_customize: 'Customization',
    editor_title: 'Channel customization',
    editor_basic_info: 'Basic info',
    editor_name: 'Name',
    editor_handle: 'Handle',
    editor_description: 'Description',
    editor_avatar: 'Avatar URL',
    editor_banner: 'Banner URL',
    editor_save: 'Publish',
    editor_cancel: 'Cancel',
    editor_success: 'Changes published successfully!',
    upload_type: 'Content Type',
    upload_video: 'Video',
    upload_shorts: 'Shorts',
    channel_loading: 'Loading channel...',
    channel_not_found: 'Channel Not Found',
    channel_not_found_desc: 'This channel doesn\'t exist or hasn\'t uploaded any videos yet.',
    channel_subscribers: 'subscribers',
    channel_videos: 'videos',
    channel_videos_tab: 'Videos',
    channel_your_channel: 'Your Channel',
    channel_no_videos: 'This channel has no videos.',
    admin_reports: 'Security Reports',
    admin_video: 'Video',
    admin_reason: 'Reason',
    admin_reporter: 'Reporter',
    admin_actions: 'Actions',
    admin_report_success: 'Report submitted successfully.',
    admin_report_fail: 'Failed to submit report.',
    admin_no_reports: 'No reports found.',
    report_reason_inappropriate: 'Inappropriate content',
    report_reason_spam: 'Spam or misleading',
    report_reason_hate: 'Hate speech',
    report_reason_violence: 'Violence or harm',
    coming_soon_desc: 'This section is currently under development. Stay tuned for further updates to Icetube 2.0 where we will launch user libraries, personalized history, and advanced upload capabilities!',
    page_watch_later: 'Watch Later',
    page_liked: 'Liked videos',
    page_clips: 'Clips',
    page_music: 'Music',
    page_movies: 'Movies & TV',
    page_live: 'Live',
    page_premium: 'Icetube Premium',
    page_yt_music: 'Icetube Music',
    page_yt_kids: 'Icetube Kids',
    page_downloads: 'Downloads',
    page_history: 'History',
    page_playlists: 'Playlists',
    page_library: 'Library',
    page_continue_watching: 'Continue watching',
    page_feature: 'Feature'
  },
  ru: {
    nav_home: 'Главная',
    nav_explore: 'Навигатор',
    nav_shorts: 'Shorts',
    nav_subscriptions: 'Подписки',
    nav_trending: 'В тренде',
    nav_library: 'Библиотека',
    nav_history: 'История',
    nav_continue_watching: 'Продолжить просмотр',
    nav_you: 'Вы',
    nav_your_channel: 'Мой канал',
    nav_playlists: 'Плейлисты',
    nav_your_videos: 'Ваши видео',
    nav_favorites: 'Избранное',
    favorites_title: 'Избранные видео',
    favorites_empty: 'Вы еще не сохранили видео. Сохраненные видео будут появляться здесь.',
    history_title: 'История',
    history_empty: 'История просмотров пуста.',
    history_clear: 'Очистить историю просмотров',
    history_clear_confirm: 'Вы уверены, что хотите полностью очистить историю просмотров?',
    liked_title: 'Понравившиеся',
    liked_empty: 'Вы еще не поставили лайк ни одному видео.',
    liked_login_required: 'Пожалуйста, войдите, чтобы увидеть понравившиеся видео.',
    nav_top_channels: 'Топ каналов',
    top_channels_title: 'Рейтинг каналов',
    top_channels_by_subs: 'По подписчикам',
    top_channels_by_views: 'По просмотрам',
    top_channels_by_likes: 'По лайкам',
    top_channels_by_videos: 'По видео',
    top_channels_empty: 'Данных для рейтинга пока нет.',
    nav_downloads: 'Скачанные',
    nav_clips: 'Клипы',
    nav_watch_later: 'Смотреть позже',
    nav_navigator: 'Навигатор',
    nav_music: 'Музыка',
    nav_movies: 'Фильмы и сериалы',
    nav_live: 'Трансляции',
    nav_more_features: 'Другие возможности',
    nav_premium: 'Icetube Premium',
    nav_yt_music: 'Icetube Music',
    nav_yt_kids: 'Icetube Детям',
    nav_liked: 'Понравившиеся',
    nav_settings: 'Настройки',
    nav_admin: 'Админка',
    nav_sign_in: 'Войти',
    nav_sign_out: 'Выйти',
    nav_subscriptions_header: 'Подписки',
    nav_socials: 'Наши соцсети',
    nav_telegram: 'Telegram канал',
    nav_show_more: 'Развернуть',
    nav_upload: 'Загрузить',
    search_placeholder: 'Поиск Icetube...',
    hero_no_videos: 'Видео пока нет',
    hero_upload_prompt: 'Будьте первым, кто загрузит видео с помощью кнопки в углу!',
    your_vids_title: 'Ваши видео',
    your_vids_subtitle: 'Управляйте своим контентом',
    your_vids_upload_btn: 'Загрузить видео',
    your_vids_login_req: 'Требуется вход',
    your_vids_login_desc: 'Вам нужно войти в аккаунт, чтобы управлять своими видео.',
    settings_title: 'Настройки',
    settings_subtitle: 'Настройки сохраняются автоматически',
    settings_theme: 'Тема оформления',
    settings_theme_desc: 'Выберите визуальный стиль сайта',
    settings_dark: 'Темная',
    settings_light: 'Светлая',
    settings_lang: 'Язык',
    settings_lang_desc: 'Выберите язык интерфейса',
    settings_ru: 'Русский',
    settings_en: 'English',
    video_views: 'просмотров',
    video_recently: 'Недавно',
    video_no_description: 'Описание отсутствует.',
    nav_studio: 'Студия Icetube',
    studio_title: 'Аналитика канала',
    studio_total_views: 'Всего просмотров',
    studio_total_videos: 'Всего видео',
    studio_content: 'Контент канала',
    studio_edit: 'Изменить',
    studio_delete: 'Удалить',
    video_no_results: 'Ничего не найдено',
    video_search_try_again: 'Попробуйте другой запрос или категорию',
    video_connecting: 'Подключаемся к льдине...',
    video_comments: 'комментариев',
    video_sign_in_comment: 'Войдите, чтобы оставить комментарий',
    video_not_found: 'Видео не найдено',
    video_not_found_desc: 'Возможно, ролик был удален или его не существует.',
    video_subscribers: 'подписчиков',
    video_subscribed: 'Вы подписаны',
    video_subscribe: 'Подписаться',
    video_share: 'Поделиться',
    video_save: 'Сохранить',
    video_saved: 'Сохранено',
    video_add_to_playlist: 'В плейлист',
    video_watch_later: 'Смотреть позже',
    video_added_to_watch_later: 'В очереди',
    watch_later_title: 'Смотреть позже',
    watch_later_empty: 'Список "Смотреть позже" пуст. Добавляйте сюда видео, которые хотите посмотреть позже.',
    video_snowflakes: 'Снежинки',
    video_views_time: 'просмотров • {time} назад',
    video_more: '...ещё',
    video_less: 'Свернуть',
    comment_sort: 'Упорядочить',
    comment_translate: 'Перевести на русский',
    comment_edit: 'Изменить',
    comment_delete: 'Удалить',
    comment_reply: 'Ответить',
    comment_save: 'Сохранить',
    comment_cancel: 'Отмена',
    comment_placeholder: 'Оставьте комментарий...',
    comment_reply_placeholder: 'Напишите ответ...',
    studio_video_header: 'Видео',
    studio_date_header: 'Дата',
    studio_views_header: 'Просмотры',
    studio_no_videos: 'Видео не найдено. Загрузите свой первый ролик!',
    studio_back_home: 'На главную',
    studio_customize: 'Настройка канала',
    editor_title: 'Настройка канала',
    editor_basic_info: 'Основные сведения',
    editor_name: 'Название',
    editor_handle: 'Псевдоним',
    editor_description: 'Описание',
    editor_avatar: 'Ссылка на аватар',
    editor_banner: 'Ссылка на шапку профиля',
    editor_save: 'Опубликовать',
    editor_cancel: 'Отмена',
    editor_success: 'Изменения успешно опубликованы!',
    upload_type: 'Тип контента',
    upload_video: 'Видео',
    upload_shorts: 'Shorts',
    channel_loading: 'Загрузка канала...',
    channel_not_found: 'Канал не найден',
    channel_not_found_desc: 'Этот канал не существует или еще не загрузил видео.',
    channel_subscribers: 'подписчиков',
    channel_videos: 'видео',
    channel_videos_tab: 'Видео',
    channel_your_channel: 'Ваш канал',
    channel_no_videos: 'На этом канале нет видео.',
    admin_reports: 'Жалобы',
    admin_video: 'Видео',
    admin_reason: 'Причина',
    admin_reporter: 'Отправитель',
    admin_actions: 'Действия',
    admin_report_success: 'Жалоба успешно отправлена.',
    admin_report_fail: 'Не удалось отправить жалобу.',
    admin_no_reports: 'Жалоб пока нет.',
    report_reason_inappropriate: 'Непристойный контент',
    report_reason_spam: 'Спам или обман',
    report_reason_hate: 'Враждебные высказывания',
    report_reason_violence: 'Насилие или вред',
    coming_soon_desc: 'Этот раздел находится в разработке. Следите за обновлениями Icetube 2.0, в которых мы запустим пользовательские библиотеки, персонализированную историю и расширенные возможности загрузки!',
    page_watch_later: 'Смотреть позже',
    page_liked: 'Понравившиеся',
    page_clips: 'Клипы',
    page_music: 'Музыка',
    page_movies: 'Фильмы и сериалы',
    page_live: 'Трансляции',
    page_premium: 'Icetube Premium',
    page_yt_music: 'Icetube Music',
    page_yt_kids: 'Icetube Детям',
    page_downloads: 'Скачанные',
    page_history: 'История',
    page_playlists: 'Плейлисты',
    page_library: 'Библиотека',
    page_continue_watching: 'Продолжить просмотр',
    page_feature: 'Функция'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
